### ISSUE TITLE
VictoriaMetrics -> VictoriaMetrics migration

### ISSUE THREAD

**Issue by beorn-** [VictoriaMetrics/vmctl#6]
Our setup is quite simple : `exporters -> prometheus -> VictoriaMetrics  <- promxy <- grafana <- users`

Here is a scenario that i wish to be able to do. Let two victoria metrics instances A and B.

stop instance A : ok
wait for some time : ok
start instance A : ok
stop instance B : not ok

the gap is there. So i wish i could backfill/override instance A with data from instance B during the gap. so even if there's a new rolling restart we shall not see the gap.

This would help achieve a very simple and naive HA

**Comment by beorn-** [comment]
off course... this task could be automated ;)

**Comment by valyala** [comment]
Note that the stop-start sequence described above shouldn't lead to data gaps on instance A and B if each instance is stopped for less than 2 hours. In this case Prometheus should fill gaps as soon as VM instance returns to operation. See [this article](https://grafana.com/blog/2019/03/25/whats-new-in-prometheus-2.8-wal-based-remote-write/) for details. If downtime for each instance exceeds 5 minutes, then response cache on the instance must be reset after Prometheus finishes backfilling in order to remove incomplete responses - see [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#backfilling) for details.

It is worth noting that [cluster version of VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md) is free from the issue described above, since `vminsert` re-routes incoming data to available `vmstorage` nodes if the destination node is temporarily unavailable.

**Comment by valyala** [comment]
An additional note - VictoriaMetrics supports de-duplication for data ingested from identically configured Prometheus instances. This should protect from gaps when one of the Prometheus instances are temporarily unavailable. See [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#deduplication) for details.

**Comment by beorn-** [comment]
> Note that the stop-start sequence described above shouldn't lead to data gaps on instance A and B if each instance is stopped for less than 2 hours. In this case Prometheus should fill gaps as soon as VM instance returns to operation. See [this article](https://grafana.com/blog/2019/03/25/whats-new-in-prometheus-2.8-wal-based-remote-write/) for details. If downtime for each instance exceeds 5 minutes, then response cache on the instance must be reset after Prometheus finishes backfilling in order to remove incomplete responses - see [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#backfilling) for details.

I'll add this and re-run a test.
 
> It is worth noting that [cluster version of VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md) is free from the issue described above, since `vminsert` re-routes incoming data to available `vmstorage` nodes if the destination node is temporarily unavailable.

If i am not mistaken the clustered version does not handle data replication and recovery whenever a storage node looses its data. It supposes that the underlying storage does it.

**Comment by valyala** [comment]
> If i am not mistaken the clustered version does not handle data replication and recovery whenever a storage node looses its data. It supposes that the underlying storage does it

Correct. This is described [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#replication-and-data-safety).

**Comment by beorn-** [comment]
> > If i am not mistaken the clustered version does not handle data replication and recovery whenever a storage node looses its data. It supposes that the underlying storage does it
> 
> Correct. This is described [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#replication-and-data-safety).

That's the only reason why we did not go down that path

**Comment by valyala** [comment]
Update - new versions of VictoriaMetrics cluster supports data replication - see [these docs](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#replication-and-data-safety) for details. Note that it doesn't support data healing yet - if data on a single `vmstorage` node is lost, then the cluster won't recover replication factor for the lost data, i.e. the number of replicas for the lost data decreases by 1 in this case.

**Comment by hagen1778** [comment]
Feature for migrating data between VM instances was added in https://github.com/VictoriaMetrics/vmctl/releases/tag/0.3.0
